### ISSUE TITLE
more option for acp?

### ISSUE THREAD

**Issue by eunaumtenhoid** [phpbb-extensions/topicprefixes#11]
option for:
1 edit prefix on acp
2 copy all prefix to other forum

Will this extension be posted on the site as an official? like ads and the others?

**Comment by VSEphpbb** [comment]
Prefix will not be editable, there is no point. Since all there is to a prefix is its name, it's actually easier (less clicks) to just create a new one and delete an old one, rather than editing it.

Also, since prefixes are not actually stored anywhere when used, just inserted into the post title, if you were able to edit a prefix, it would not change for any posts that used it, so again that's another reason there's no point in editing them.

Copy all prefix to other forum is something to consider...but not all. Possibly marking them but that's not really much of a priority IMO, as mentioned before it's so easy to create them in the first place.

No, this will not be released at it is very simple and was created just for phpbb.com's needs, and because there is potential for something much better to be created out there in the community, like: https://www.phpbb.com/community/viewtopic.php?f=456&t=2209726
